# SPDX-License-Identifier: BSD-3-Clause
---
default: true
MD004: false
MD010: false
MD013: false
MD024: false
MD029:
  style: one
MD033:
  allowed_elements:
    - img
    - br
MD034: false
MD035: false
MD041: false
MD046:
  style: fenced
MD048:
  style: backtick
