name: Linter Actions Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  checkpatch:
    name: Checkpatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkpatch
        uses: open-education-hub/actions/checkpatch@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Super Linter
        uses: open-education-hub/actions/super-linter@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Typos
        uses: crate-ci/typos@v1.28.3
        with:
          config: .github/.typos.toml
